### ISSUE TITLE
Postgres authentication issues

### ISSUE THREAD

**Issue by ethamitc** [PathfindersMC/API#8]
```
(node:696) UnhandledPromiseRejectionWarning: SequelizeConnectionError: password authentication failed for user "pathfinders"
    at A:\Development\Pathfinders-API\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:182:24
    at Connection.connectingErrorHandler (A:\Development\Pathfinders-API\node_modules\pg\lib\client.js:213:14)
    at Connection.emit (events.js:310:20)
    at A:\Development\Pathfinders-API\node_modules\pg\lib\connection.js:109:10
    at Parser.parse (A:\Development\Pathfinders-API\node_modules\pg-protocol\dist\parser.js:42:17)
    at Socket.<anonymous> (A:\Development\Pathfinders-API\node_modules\pg-protocol\dist\index.js:8:42)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ethamitc** [comment]
Fixed.
